#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx-config

- name: install html configuration
  template:
    src: "html.j2"
    dest: '/usr/share/nginx/html/{{region|lower}}-site.html'
  notify: restart-nginx  
